#!/bin/bash -e
#
# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
# SPDX-License-Identifier: Apache-2.0

go run cmd/registry-migrator/main.go \
  --backup-file "$HOME/Desktop/etcd-step1.backup" \
  --old-registry-prefix "/registry/garden.sapcloud.io" \
  --new-registry-prefix "/registry-gardener" \
  --endpoints "http://localhost:32379" \
  --force=false \
  --delete=false

go run cmd/registry-migrator/main.go \
  --backup-file "$HOME/Desktop/etcd-step2.backup" \
   --old-registry-prefix "/registry-gardener/garden.sapcloud.io" \
   --new-registry-prefix "/registry-gardener/core.gardener.cloud" \
   --endpoints "http://localhost:32379" \
   --force=false \
   --delete=false
